version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.14.0

jobs:
  create-dev-folder:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Create dev folder
          command: |
            mkdir dev
            touch ./dev/orb.yml
      - persist_to_workspace:
          root: dev
          paths:
            - orb.yml

workflows:
  build:
    jobs:
      - create-dev-folder
      - orb-tools/lint:
          checkout: false
          attach-workspace: true
          workspace-root: dev
          lint-dir: dev
          requires:
            - create-dev-folder
      - orb-tools/pack:
          attach-workspace: true
          workspace-root: dev
          workspace-path: orb.yml
          source-dir: ./octo
          destination-orb-path: /dev/orb.yml
          artifact-path: dev
          requires:
            - orb-tools/lint
