version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.14.0

jobs:
  create-dev-folder:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Create dev folder
          command: |
            apt-get update && apt-get install -y ca-certificates
            mkdir dev
            touch ./dev/orb.yml
      - persist_to_workspace:
          root: dev
          paths:
            - orb.yml

workflows:
  build:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          checkout: true
          orb-name: octopus-samples/octo-exp
          orb-path: orb.yml
          publish-alpha-version: false
          publish-sha-version: false
          publish-branch-sha-version: true
          requires:
            - orb-tools/lint
