version: 2.1

description: |
  Experimental orb for working with the Octopus CLI.
display:
  source_url: https://github.com/OctopusSamples/octo-exp-orb
  home_url: https://github.com/OctopusSamples/octo-exp-orb

executors:
  default:
    description: |
      Use the base CircleCI image by default
    docker:
      - image: cimg/base:stable
examples:
  install-tools:
    description: Install the Octo CLI on the container.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - checkout
  pack:
    description: Create an Octopus package.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - checkout
            - octo-exp/pack:
                id: "OctopusSamples.OctoPetShop.Database"
                version: "1.2.3"
                base_path: "publish/OctopusSamples.OctoPetShop.Database"
                out_folder: "package"
  push:
    description: Push a package to Octopus.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - checkout
            - octo-exp/push:
                package: "package/OctopusSamples.OctoPetShop.Database.1.2.3.zip"
                server: "OCTOPUS_SERVER_URL"
                api_key: "OCTOPUS_API_KEY"
  build-information:
    description: Create and upload build-information to Octopus.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - octo-exp/build-information:
                package_id: "OctopusSamples.OctoPetShop.Database"
                version: "1.2.3"
                server: "https://youroctopusserver.com"
                api_key: "API-YOURAPIKEY"
  create-release:
    description: Create an Octopus release.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - octo-exp/create-release:
                project: "OctoPetShop"
                release_number: "1.2.3"
                server: "https://youroctopusserver.com"
                api_key: "API-YOURAPIKEY"
  deploy-release:
    description: Deploy an existing Octopus release.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - octo-exp/deploy-release:
                project: "OctoPetShop"
                release_number: "1.2.3"
                deploy_to: "Development"
                progress: true
                server: "https://youroctopusserver.com"
                api_key: "API-YOURAPIKEY"
  promote-release:
    description: Promote a release in one environment to another.
    usage:
      version: 2.1
      orbs:
        octo-exp: octopus-samples/octo-exp@0.0.3
      jobs:
        build:
          executor:
            name: octo-exp/default
          steps:
            - octo-exp/install-tools
            - octo-exp/deploy-release:
                project: "OctoPetShop"
                from: "Development"
                to: "Test"
                progress: true
                server: "https://youroctopusserver.com"
                api_key: "API-YOURAPIKEY"
